Repository vaexio/vaex, pull requests merged in 2020-04, with the labels that each got.

#600 Fix: dropna issue when no columns are specified.
  CHANGELOG.md
  packages/vaex-core/vaex/dataframe.py
  tests/dropna_test.py
Labels: priority: medium

#669 `df.isin` fix for dtype object
  CHANGELOG.md
  packages/vaex-core/vaex/functions.py
  tests/isin_test.py
Labels: priority: high

#593 Make df.column_count to not count hidden columns
  CHANGELOG.md
  packages/vaex-core/vaex/dataframe.py
  tests/column_test.py
Labels: priority: medium

#531 Fix head/tail for concatenated DataFrames with missing values
  tests/concat_test.py
Labels: priority: medium

#640 Fix: evaluation of a dataframe containing masked arrays
  packages/vaex-core/vaex/dataframe.py
  tests/values_test.py
Labels: priority: high

#592 Fix state transfer after rewriting virtual columns
  packages/vaex-core/vaex/dataframe.py
  tests/state_test.py
Labels: bug, priority: medium

#651 Fix: `count` issue with `limits='minmax'`
  CHANGELOG.md
  packages/vaex-core/vaex/dataframe.py
  tests/count_test.py
Labels: bug, priority: high

#527 Improve the API for the percentile_approx dataframe method
  CHANGELOG.md
  packages/vaex-core/vaex/dataframe.py
  tests/percentile_approx_test.py
Labels: priority: medium

#639 Fix: inconsistent evaluation in to_arrow_table
  packages/vaex-arrow/vaex_arrow/convert.py
  tests/arrow/to_arrow_table_test.py
Labels: priority: high

#701 chore: run benchmarks on dedicated hardware
  benchmarks/README.rst
  bin/benchmark_new_commits.sh
Labels: performance
